import 'package:body_buddies/features/workouts/domain/Entities/exercise_entity.dart';
import 'package:body_buddies/features/workouts/domain/Entities/workout_entity.dart';

class FakeWorkoutsDatabase {
  List<WorkoutEntity> fakeWorkoutEntities = [
    WorkoutEntity(
      title: "Тяжёлая среда",
      weekday: 2,
      back: true,
      triceps: true,
      exercises: [
        ExerciseEntity(
            isExercise: true,
            title: "Подтягивания",
            kilograms: 30,
            restTimeInMinutes: 3,
            restTimeInSeconds: 0,
            sets: 5,
            reps: 6),
        ExerciseEntity(
            isExercise: true,
            title: "Тяга штанги в наклоне",
            kilograms: 75,
            sets: 4,
            reps: 6,
            restTimeInSeconds: 0,
            restTimeInMinutes: 3),
        ExerciseEntity(
            isExercise: true,
            title: "Тяга широчайшей (верх. блок)",
            kilograms: 47.5,
            sets: 4,
            reps: 6,
            restTimeInMinutes: 3,
            restTimeInSeconds: 0),
        ExerciseEntity(
            isExercise: true,
            title: "Жим трицепс (верх. блок)",
            kilograms: 67.5,
            reps: 6,
            sets: 4,
            restTimeInMinutes: 2,
            restTimeInSeconds: 0),
        ExerciseEntity(
            isExercise: true,
            title: "Французский жим",
            kilograms: 37.5,
            reps: 8,
            sets: 3,
            restTimeInMinutes: 2,
            restTimeInSeconds: 0),
      ],
    ),
    WorkoutEntity(
      title: "Легкая ноги",
      weekday: 4,
      legs: true,
      shoulders: true,
      exercises: [
        ExerciseEntity(
            isExercise: true,
            title: "Икры штанга",
            kilograms: 70,
            restTimeInMinutes: 3,
            restTimeInSeconds: 0,
            sets: 4,
            reps: 20),
        ExerciseEntity(
            isExercise: true,
            title: "Жим лёжа",
            kilograms: 65,
            sets: 4,
            reps: 10,
            restTimeInSeconds: 0,
            restTimeInMinutes: 3),
        ExerciseEntity(
            isExercise: true,
            title: "Квадры в тренажёре",
            kilograms: 70,
            sets: 4,
            reps: 15,
            restTimeInMinutes: 3,
            restTimeInSeconds: 0),
        ExerciseEntity(
            isExercise: true,
            title: "Бицепс бедра",
            kilograms: 30,
            reps: 12,
            sets: 4,
            restTimeInMinutes: 3,
            restTimeInSeconds: 0),
        ExerciseEntity(
            isExercise: true,
            title: "Приседания",
            kilograms: 60,
            reps: 12,
            sets: 4,
            restTimeInMinutes: 3,
            restTimeInSeconds: 0),
        ExerciseEntity(
            isExercise: true,
            title: "Армейский жим",
            kilograms: 30,
            reps: 12,
            sets: 4,
            restTimeInMinutes: 2,
            restTimeInSeconds: 0),
        ExerciseEntity(
            isExercise: true,
            title: "Махи гантелями",
            kilograms: 17.5,
            reps: 20,
            sets: 4,
            restTimeInMinutes: 2,
            restTimeInSeconds: 0),
      ],
    ),
    WorkoutEntity(
        title: "Timer Exerc",
        exercises: [
          ExerciseEntity(
              isTimerExercise: true,
              title: "Берпс",
              kilograms: 5,
              restTimeInMinutes: 0,
              restTimeInSeconds: 5,
              timerTimeMinutes: 0,
              timerTimeSeconds: 10,
              sets: 3),
        ],
        weekday: 2,
        legs: true,
        cardio: true),
    WorkoutEntity(
      title: "Ношке наказание",
      weekday: 1,
      legs: true,
      shoulders: true,
      exercises: [
        ExerciseEntity(
            isExercise: true,
            title: "Икры штанга",
            kilograms: 70,
            restTimeInMinutes: 3,
            restTimeInSeconds: 0,
            sets: 4,
            reps: 20),
        ExerciseEntity(
            isExercise: true,
            title: "Жим лёжа",
            kilograms: 75,
            sets: 4,
            reps: 10,
            restTimeInSeconds: 0,
            restTimeInMinutes: 3),
        ExerciseEntity(
            isExercise: true,
            title: "Квадры в тренажёре",
            kilograms: 85,
            sets: 4,
            reps: 15,
            restTimeInMinutes: 3,
            restTimeInSeconds: 0),
        ExerciseEntity(
            isExercise: true,
            title: "Бицепс бедра",
            kilograms: 35,
            reps: 12,
            sets: 4,
            restTimeInMinutes: 3,
            restTimeInSeconds: 0),
        ExerciseEntity(
            isExercise: true,
            title: "Приседания",
            kilograms: 65,
            reps: 12,
            sets: 4,
            restTimeInMinutes: 3,
            restTimeInSeconds: 0),
        ExerciseEntity(
            isExercise: true,
            title: "Армейский жим",
            kilograms: 42.5,
            reps: 12,
            sets: 4,
            restTimeInMinutes: 2,
            restTimeInSeconds: 0),
        ExerciseEntity(
            isExercise: true,
            title: "Махи гантелями",
            kilograms: 25,
            reps: 20,
            sets: 4,
            restTimeInMinutes: 2,
            restTimeInSeconds: 0),
      ],
    ),
  ];

  List<WorkoutEntity> journalSavedWorkouts = [
    WorkoutEntity(
        title: "Среда второго понедельника",
        exercises: [
          ExerciseEntity(
              isExercise: true,
              title: "Приседания",
              kilograms: 60,
              reps: 12,
              sets: 4,
              restTimeInMinutes: 3,
              restTimeInSeconds: 0),
          ExerciseEntity(
              isExercise: true,
              title: "Армейский жим",
              kilograms: 30,
              reps: 12,
              sets: 4,
              restTimeInMinutes: 2,
              restTimeInSeconds: 0),
          ExerciseEntity(
              isExercise: true,
              title: "Махи гантелями",
              kilograms: 17.5,
              reps: 20,
              sets: 4,
              restTimeInMinutes: 2,
              restTimeInSeconds: 0),
        ],
        dateWhenTodo: "08.02.2025"),
  ];

  WorkoutEntity getWorkout(int index) => fakeWorkoutEntities[index];
}
